language: ruby

rvm:
  - 2.3.3
  - 2.2.6
  - 2.1.9

sudo: false

services: mongodb

before_install:
 - gem update --system
 - gem install bundler

before_script:
  - mysql -e 'CREATE DATABASE statesman_test;'
  - psql -c 'CREATE DATABASE statesman_test;' -U postgres

script:
  - bundle exec rubocop
  - bundle exec rake

env:
  - "RAILS_VERSION=3.2.21"
  - "RAILS_VERSION=4.0.13"
  - "RAILS_VERSION=4.1.14"
  - "RAILS_VERSION=4.2.5"
  - "RAILS_VERSION=4.2.5 DATABASE_URL=mysql2://root@localhost/statesman_test"
  - "RAILS_VERSION=4.2.5 DATABASE_URL=postgres://postgres@localhost/statesman_test"
  - "RAILS_VERSION=5.0.0 EXCLUDE_MONGOID=true"

matrix:
  exclude:
    - rvm: 2.1.9
      env: "RAILS_VERSION=5.0.0 EXCLUDE_MONGOID=true"
